name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.0.1, etc.
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        cache: true
        
    - name: Create .env file
      working-directory: ./app
      run: |
        echo "CLOUDFLARE_AI_URL=${{ secrets.CLOUDFLARE_AI_URL }}" >> .env
        echo "CLOUDFLARE_AI_TOKEN=${{ secrets.CLOUDFLARE_AI_TOKEN }}" >> .env
        
    - name: Get Flutter dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Analyze Flutter code
      working-directory: ./app
      run: flutter analyze
      
    - name: Run Flutter tests
      working-directory: ./app
      run: flutter test
      
    - name: Build Debug APK
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      working-directory: ./app
      run: flutter build apk --debug
      
    - name: Build Release APK
      if: startsWith(github.ref, 'refs/tags/')
      working-directory: ./app
      run: flutter build apk --release
      
    - name: Upload Debug APK
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 7
        
    - name: Upload Release APK as Artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - uses: ncipollo/release-action@v1
      with:
        artifacts: app/build/app/outputs/flutter-apk/app-release.apk
        name: BeMyGuide ${{ github.ref_name }}
        body: |
          ## 📱 Download
          - **APK**: `app-release.apk` (Android)

          ## 🔧 Build Info
          - **Flutter Version**: 3.29.3
          - **Build Type**: Release
          - **Commit**: ${{ github.sha }}

          ## 📋 Installation
          1. Download the APK file
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install the APK on your device

          ---
          *Generated automatically by GitHub Actions*
        generateReleaseNotes: true
